[colors.primary]
background = "#1A1A1A"
foreground = "#CCCCCC"

[colors.cursor]
text = "CellBackground"
cursor = "CellForeground"

[colors.vi_mode_cursor]
text = "#1A1A1A"
cursor = "#FC725D"

[colors.search.matches]
foreground = "#1A1A1A"
background = "#C8904B"

[colors.search.focused_match]
foreground = "#1A1A1A"
background = "#DBAA6E"

[colors.hints.start]
foreground = "#1A1A1A"
background = "#DBAA6E"

[colors.hints.end]
foreground = "#1A1A1A"
background = "#DBAA6E"

[colors.line_indicator]
foreground = "#1A1A1A"
background = "#C8904B"

[colors.footer_bar]
foreground = "#1A1A1A"
background = "#C8904B"

[colors.selection]
text = "CellForeground"
background = "#333333"

[colors.normal]
black = "#1A1A1A"
red = "#FC725D"
green = "#8BAB60"
yellow = "#C8904B"
blue = "#72A4C7"
magenta = "#B980C7"
cyan = "#62B599"
white = "#B3B3B3"

[colors.bright]
black = "#666666"
red = "#FF907E"
green = "#9EC585"
yellow = "#DBAA6E"
blue = "#91BCDB"
magenta = "#CE9DDB"
cyan = "#83CBB3"
white = "#CCCCCC"

[colors.dim]
black = "#666666"
red = "#C93F2A"
green = "#58782D"
yellow = "#955D18"
# blue = "#3F7194"
magenta = "#864D94"
cyan = "#2F8266"
white = "#999999"
